Add License to files
Former-commit-id: 74cdeb3a8cac69b1622ef45d11cea88c0646502f

diff --git a/scripts/downloaders/down-config b/scripts/downloaders/down-config
--- a/scripts/downloaders/down-config
+++ b/scripts/downloaders/down-config
@@ -1,8 +1,23 @@
 #!/bin/bash
 # shellcheck shell=bash disable=1091
-#Import libraries
+
+# Copyright The Red Cyclops © 2023
+# This program is free software: you can redistribute it and/or modify it under the terms of
+# the GNU General Public License as published by the Free Software Foundation,
+# either version 3 of the License, or (at your option) any later version.
+# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
+# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+# See the GNU General Public License for more details.
+# You should have received a copy of the GNU General Public License along with this program.
+# If not, see <https://www.gnu.org/licenses/>.
+
+# Import libraries
 source "$MUSICBOX_BIN_DIR/formatlib"
 source "$MUSICBOX_BIN_DIR/gdrivelib"
-#download
-downloadfile "$(getfileid 'Configuration')" "$MUSICBOX_TMP_DIR/dirty-config"
+# Download
+if downloadfile "$(getfileid 'Configuration')" "$MUSICBOX_TMP_DIR/dirty-config"; then
 grep -v '#.*' "$MUSICBOX_TMP_DIR/dirty-config" > "$MUSICBOX_CONFIG_DIR"/config
+else
+error "Configuration file not found!"
+exit 1
+fi
