Minor bugfixes and spellcheck
Former-commit-id: 34304e96ee5e31aba96b665e0fc5b090f7096568

diff --git a/scripts/setup/install b/scripts/setup/install
--- a/scripts/setup/install
+++ b/scripts/setup/install
@@ -28,13 +28,20 @@
     # Add them to the default enviroment
     cp "$installpath/scripts/musicbox-env" /usr/lib/environment.d/musicbox.conf && info "Enviroment has been added to default"
 # Create all directories [WORKING]
-mkdir -p "$MUSICBOX_BIN_DIR" && info "Created $MUSICBOX_BIN_DIR Successfully"
-mkdir -p "$MUSICBOX_LOG_DIR" && info "Created $MUSICBOX_LOG_DIR Successfully"
-mkdir -p "$MUSICBOX_TMP_DIR" && info "Created $MUSICBOX_TMP_DIR Successfully"
-mkdir -p "$MUSICBOX_CFG_DIR" && info "Created $MUSICBOX_CFG_DIR Successfully"
-mkdir -p "$MUSICBOX_CACHE_DIR" && info "Created $MUSICBOX_CACHE_DIR Successfully"
+if mkdir -p "$MUSICBOX_BIN_DIR"; then info "Created $MUSICBOX_BIN_DIR Successfully"; else error "Failed to create $MUSICBOX_BIN_DIR"; fi
+if mkdir -p "$MUSICBOX_LOG_DIR"; then info "Created $MUSICBOX_LOG_DIR Successfully"; else error "Failed to create $MUSICBOX_LOG_DIR"; fi
+if mkdir -p "$MUSICBOX_TMP_DIR"; then info "Created $MUSICBOX_TMP_DIR Successfully"; else error "Failed to create $MUSICBOX_TMP_DIR"; fi
+if mkdir -p "$MUSICBOX_CFG_DIR"; then info "Created $MUSICBOX_CFG_DIR Successfully"; else error "Failed to create $MUSICBOX_CFG_DIR"; fi
+if mkdir -p "$MUSICBOX_CACHE_DIR"; then info "Created $MUSICBOX_CACHE_DIR Successfully"; else error "Failed to create $MUSICBOX_CACHE_DIR"; fi
+# Add DNS servers if --dnsfix is passed
+if [[ $1 == "--dnsfix" ]]; then
+    echo "nameserver 9.9.9.9" > /etc/resolv.conf
+    echo "dns-nameserver 9.9.9.9" >> /etc/network/interfaces
+fi
+# Check that the internet is working
+    if ! ping -c 1 debian.org; then critical "Couldn't connect to the internet, exiting..."; exit 1; fi
 # Install packages [WORKING]
-    apt -y install ffmpeg mp3gain mp3val pulseaudio pulseaudio-utils vlc  mp3info unzip
+    apt -y install ffmpeg mp3gain mp3val pulseaudio pulseaudio-utils vlc mp3info unzip wget
         # Download and install gdrive
         # Create a temporary directory to store the download
         tmpdir=$(mktemp -d)
@@ -54,11 +61,12 @@ mkdir -p "$MUSICBOX_CACHE_DIR" && info "Created $MUSICBOX_CACHE_DIR Successfully
         chmod +x /usr/local/bin/yt-dlp
 # Unpack the credentials
     echo "Getting Credentials"
-    unzip "$installpath/creds.zip" -d "$installpath/creds"
+    credpath=$(mktemp -d)
+    echo $credpath
+    chmod 700 "${credpath:?}"
+    unzip "$installpath/creds.zip" -d "${credpath:?}" || error "Failed to extract credentials"
 # Enable cron
     systemctl enable --now cron
-# Enable pulseaudio
-    systemctl enable --now pulseaudio.socket
 # Add unprivileged user
     adduser --home "$MUSICBOX_USER_DIR" --system --shell /bin/bash "$MUSICBOX_USER"
     # Give it access to all the needed directories
@@ -70,14 +78,14 @@ mkdir -p "$MUSICBOX_CACHE_DIR" && info "Created $MUSICBOX_CACHE_DIR Successfully
     chown "$MUSICBOX_USER" "$MUSICBOX_USER_DIR"
 
     # Copy drive credentials to home
-    cp "$installpath/creds/gdrive_export-***REMOVED***.tar" "$MUSICBOX_USER_DIR"
+    cp "$credpath/gdrive_export-***REMOVED***.tar" "$MUSICBOX_USER_DIR"
     # Give permision to the user to import them
-    chown "$MUSICBOX_USER" "$installpath/creds/gdrive_export-***REMOVED***.tar"
+    chown "$MUSICBOX_USER" "$MUSICBOX_USER_DIR/gdrive_export-***REMOVED***.tar"
     # Setup drive access
     su -l "$MUSICBOX_USER" -s "/bin/bash" -c "$MUSICBOX_BIN_DIR/gdrive account import $MUSICBOX_USER_DIR/gdrive_export-***REMOVED***.tar"
-    su -l "$MUSICBOX_USER" -s "/bin/bash" -c "$MUSICBOX_BIN_DIR/gdrive account switch ***REMOVED***"
-    # Remove drive credentials from home
+    # Remove credentials file
     rm "$MUSICBOX_USER_DIR/gdrive_export-***REMOVED***.tar"
+    rm -R "$credpath"
 
 # Setup default crontabs
     # Root Crontab
@@ -85,10 +93,11 @@ mkdir -p "$MUSICBOX_CACHE_DIR" && info "Created $MUSICBOX_CACHE_DIR Successfully
     # User Crontab
     crontab -u "$MUSICBOX_USER" "$installpath/cron/usercron.txt"
 # Copy scripts to bin
-    # Makes all scripts executable
-    chmod -R +x "$installpath/scripts/"*
     # Gets all files and sends them as arguments to copy that copies them to the binaries directory
     find "$installpath/scripts" -type f -exec cp {} "$MUSICBOX_BIN_DIR/" \; && info "Copied scripts to $MUSICBOX_BIN_DIR"
-
+    # Make all scripts executable
+    chmod -R +x "$MUSICBOX_BIN_DIR"
+#Create checksums for integrity testing
+sha1sum "$MUSICBOX_BIN_DIR"/* > $MUSICBOX_CFG_DIR/sha1sums
 
 info "Instalation Finished"
