Add a bit of error handeling
Former-commit-id: 25152015215193bad7583ff65e7ae7ef1a45dfad

diff --git a/scripts/scheduler b/scripts/scheduler
--- a/scripts/scheduler
+++ b/scripts/scheduler
@@ -63,7 +63,7 @@ getsong(){
         done
         echo "$song" | tee "$MUSICBOX_CACHE_DIR"/scheduledsongs
     else
-    echo "$MUSICBOX_CACHE_DIR/extra-songs/$song"
+    echo "$MUSICBOX_CACHE_DIR/extra-songs/${song:?}" || error "Specified song not found or not parsed properly!"
     fi
 }
 # Parse schedule
